server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/tkt_bkng?createDatabaseIfNotExist=true
    username: mg
#spring:
#  datasource:
#    password: ${JDBC_DATABASE_PASSWORD}
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
jwt:
 secret: mg123
    
#   jwt.secret=mg123